PARTNER = {
    "BSX": "BSX",
    "AEVO": "AEVO",
    "HYPERLIQUID": "HYPERLIQUID",
    "HYPERLIQUID_HYPE": "HYPERLIQUID_HYPE",
    "GOLDLINK": "GOLDLINK",
}

ALLOCATION_RATIO: float = 1 / 2
AE_USD = 0.08 / 365
LST_YEILD = 0.036 / 365
RENZO_AEVO_VALUE: float = 0.065 / 365
LEVERAGE: float = 4
