"""add_vault_apy

Revision ID: 018df7cfce0f
Revises: 41409ced74bc
Create Date: 2024-09-05 08:38:39.077396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "018df7cfce0f"
down_revision: Union[str, None] = "41409ced74bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vault_apy",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("vault_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("total_apy", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["vaults.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vault_apy_component",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("vault_apy_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("component_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("component_apy", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vault_apy_id"],
            ["vault_apy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vault_apy_component")
    op.drop_table("vault_apy")
    # ### end Alembic commands ###
