"""add_index_from_address_for_transaction

Revision ID: 051f0339f486
Revises: 7e42c3186e9b
Create Date: 2024-10-09 20:38:46.050511

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "051f0339f486"
down_revision: Union[str, None] = "7e42c3186e9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_onchain_transaction_history_from_address"),
        "onchain_transaction_history",
        ["from_address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_onchain_transaction_history_from_address"),
        table_name="onchain_transaction_history",
    )
    # ### end Alembic commands ###
