"""add_app_config

Revision ID: 126a0e3cb181
Revises: 6224acb9ea09
Create Date: 2025-01-13 16:00:07.987172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "126a0e3cb181"
down_revision: Union[str, None] = "6224acb9ea09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_config",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="config",
    )
    op.add_column("vault_performance", sa.Column("apy_15d", sa.Float(), nullable=True))
    op.add_column("vault_performance", sa.Column("apy_45d", sa.Float(), nullable=True))
    op.add_column("vaults", sa.Column("apy_15d", sa.Float(), nullable=True))
    op.add_column("vaults", sa.Column("apy_45d", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vaults", "apy_45d")
    op.drop_column("vaults", "apy_15d")
    op.drop_column("vault_performance", "apy_45d")
    op.drop_column("vault_performance", "apy_15d")
    op.drop_table("app_config", schema="config")
    # ### end Alembic commands ###
