"""add underlying asset for vault

Revision ID: 33c116dedfdf
Revises: 4db661586a21
Create Date: 2024-08-29 14:34:21.239955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "33c116dedfdf"
down_revision: Union[str, None] = "4db661586a21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vaults",
        sa.Column(
            "underlying_asset", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vaults", "underlying_asset")
    # ### end Alembic commands ###
