"""add pending_deposit user position

Revision ID: 467a8686c4a3
Revises: e38a686b2086
Create Date: 2024-12-05 22:41:06.324990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '467a8686c4a3'
down_revision: Union[str, None] = 'e38a686b2086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('user_portfolio', sa.Column('pending_deposit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_portfolio', 'pending_deposit')
    # ### end Alembic commands ###
