"""add_vault_performance_history

Revision ID: 4958d1d6c7fb
Revises: 8c19a4f43231
Create Date: 2024-08-20 14:50:11.049245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4958d1d6c7fb'
down_revision: Union[str, None] = '8c19a4f43231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_performance_history',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('total_locked_value', sa.Float(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('vault_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_performance_history_datetime'), 'vault_performance_history', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_performance_history_datetime'), table_name='vault_performance_history')
    op.drop_table('vault_performance_history')
    # ### end Alembic commands ###
