"""add_apy_15days_45days

Revision ID: 4f5b21a9d1eb
Revises: 6224acb9ea09
Create Date: 2025-01-12 19:59:05.746630

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4f5b21a9d1eb"
down_revision: Union[str, None] = "6224acb9ea09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vault_performance", sa.Column("apy_15d", sa.Float(), nullable=True))
    op.add_column("vault_performance", sa.Column("apy_45d", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vault_performance", "apy_45d")
    op.drop_column("vault_performance", "apy_15d")
    # ### end Alembic commands ###
