"""add pendle market column to vault

Revision ID: 56ef659cac65
Revises: 41409ced74bc
Create Date: 2024-09-11 11:57:22.680197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "56ef659cac65"
down_revision: Union[str, None] = "41409ced74bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vaults",
        sa.Column(
            "pendle_market_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vaults", "pendle_market_address")
    # ### end Alembic commands ###
