"""add reward apy to vaults table

Revision ID: 6224acb9ea09
Revises: f46b7c39954a
Create Date: 2024-12-24 22:00:05.652436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "6224acb9ea09"
down_revision: Union[str, None] = "f46b7c39954a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "vault_performance", sa.Column("base_weekly_apy", sa.Float(), nullable=True)
    )
    op.add_column(
        "vault_performance", sa.Column("base_monthly_apy", sa.Float(), nullable=True)
    )
    op.add_column(
        "vault_performance", sa.Column("reward_weekly_apy", sa.Float(), nullable=True)
    )
    op.add_column(
        "vault_performance", sa.Column("reward_monthly_apy", sa.Float(), nullable=True)
    )
    
    op.add_column("vaults", sa.Column("base_weekly_apy", sa.Float(), nullable=True))
    op.add_column("vaults", sa.Column("base_monthly_apy", sa.Float(), nullable=True))
    op.add_column("vaults", sa.Column("reward_weekly_apy", sa.Float(), nullable=True))
    op.add_column("vaults", sa.Column("reward_monthly_apy", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vaults", "reward_monthly_apy")
    op.drop_column("vaults", "reward_weekly_apy")
    op.drop_column("vaults", "base_monthly_apy")
    op.drop_column("vaults", "base_weekly_apy")
    
    op.drop_column("vault_performance", "reward_monthly_apy")
    op.drop_column("vault_performance", "reward_weekly_apy")
    op.drop_column("vault_performance", "base_monthly_apy")
    op.drop_column("vault_performance", "base_weekly_apy")
    # ### end Alembic commands ###
