"""add_field_deposit

Revision ID: 6457d32ae825
Revises: 73e95337914d
Create Date: 2025-01-20 17:44:20.421519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "6457d32ae825"
down_revision: Union[str, None] = "73e95337914d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vault_metadata",
        sa.Column("deposit_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vault_metadata", "deposit_token")
    # ### end Alembic commands ###
