"""create model for season 2 point distribution

Revision ID: 71262c2b5073
Revises: fe968e528b4e
Create Date: 2025-02-13 14:10:55.100657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '71262c2b5073'
down_revision: Union[str, None] = 'fe968e528b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier_config',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tier_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points_required', sa.Float(), nullable=False),
    sa.Column('reward', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_held_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_rate_history',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('point_distributed', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['reward_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_season_1_points',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tier',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['tier_config.id'], ),
    sa.ForeignKeyConstraint(['user_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_time_factor',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_portfolio_id', sa.Integer(), nullable=False),
    sa.Column('time_factor', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_portfolio_id'], ['user_portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wtvl_history',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('wtvl', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['reward_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wtvl_history')
    op.drop_table('user_time_factor')
    op.drop_table('user_tier')
    op.drop_table('user_season_1_points')
    op.drop_table('base_rate_history')
    op.drop_table('tier_config')
    # ### end Alembic commands ###
