"""add onchain_transaction_history table

Revision ID: 73e06b713dec
Revises: c60cbeb13f60
Create Date: 2024-07-18 16:53:26.624949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "73e06b713dec"
down_revision: Union[str, None] = "c60cbeb13f60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onchain_transaction_history",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("tx_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.Column("from_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("to_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("method_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_onchain_transaction_history_block_number"),
        "onchain_transaction_history",
        ["block_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_onchain_transaction_history_tx_hash"),
        "onchain_transaction_history",
        ["tx_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_onchain_transaction_history_tx_hash"),
        table_name="onchain_transaction_history",
    )
    op.drop_index(
        op.f("ix_onchain_transaction_history_block_number"),
        table_name="onchain_transaction_history",
    )
    op.drop_table("onchain_transaction_history")
    # ### end Alembic commands ###
