"""add user_holding_asset_history table

Revision ID: 906f1607795a
Revises: 73e06b713dec
Create Date: 2024-07-19 22:18:25.750592

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "906f1607795a"
down_revision: Union[str, None] = "73e06b713dec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_holding_asset_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_shares", sa.Float(), nullable=False),
        sa.Column("vault_total_shares", sa.Float(), nullable=False),
        sa.Column("asset_amount", sa.Float(), nullable=False),
        sa.Column("asset_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asset_symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asset_decimals", sa.Integer(), nullable=False),
        sa.Column("holding_percentage", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "onchain_transaction_history",
        sa.Column("timestamp", sa.Integer(), nullable=True),
    )
    op.create_index(
        op.f("ix_onchain_transaction_history_timestamp"),
        "onchain_transaction_history",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_onchain_transaction_history_timestamp"),
        table_name="onchain_transaction_history",
    )
    op.drop_column("onchain_transaction_history", "timestamp")
    op.drop_table("user_holding_asset_history")
    # ### end Alembic commands ###
