"""Added default_vault_id to vaults table

Revision ID: 92c1e0784353
Revises: 9c8725467e5d
Create Date: 2024-07-14 03:39:55.491599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "92c1e0784353"
down_revision: Union[str, None] = "9c8725467e5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "vault_groups",
        sa.Column("default_vault_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vault_groups", "default_vault_id")

    # ### end Alembic commands ###
