"""Change datetime to TIMESTAMPTZ

Revision ID: 991468c3f633
Revises: cac8624add7e
Create Date: 2024-09-19 08:44:22.916396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "991468c3f633"
down_revision: Union[str, None] = "cac8624add7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "vault_performance",
        "datetime",
        existing_type=sa.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        postgresql_using="datetime AT TIME ZONE 'UTC'",
    )
    op.alter_column(
        "vault_performance_history",
        "datetime",
        existing_type=sa.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        postgresql_using="datetime AT TIME ZONE 'UTC'",
    )

    op.alter_column(
        "pps_history",
        "datetime",
        existing_type=sa.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        postgresql_using="datetime AT TIME ZONE 'UTC'",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
