"""add_report_funding_rate

Revision ID: 996b2f3d135f
Revises: a176b1b01a45
Create Date: 2024-12-07 21:34:26.744022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "996b2f3d135f"
down_revision: Union[str, None] = "a176b1b01a45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apy_rate_history",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("apy_rate", sa.Float(), nullable=False),
        sa.Column("partner_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="reports",
    )
    op.create_index(
        op.f("ix_reports_apy_rate_history_datetime"),
        "apy_rate_history",
        ["datetime"],
        unique=False,
        schema="reports",
    )
    op.create_index(
        op.f("ix_reports_apy_rate_history_partner_name"),
        "apy_rate_history",
        ["partner_name"],
        unique=False,
        schema="reports",
    )
    op.create_table(
        "funding_history",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("funding_rate", sa.Float(), nullable=False),
        sa.Column("partner_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="reports",
    )
    op.create_index(
        op.f("ix_reports_funding_history_datetime"),
        "funding_history",
        ["datetime"],
        unique=False,
        schema="reports",
    )
    op.create_index(
        op.f("ix_reports_funding_history_partner_name"),
        "funding_history",
        ["partner_name"],
        unique=False,
        schema="reports",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reports_funding_history_partner_name"),
        table_name="funding_history",
        schema="reports",
    )
    op.drop_index(
        op.f("ix_reports_funding_history_datetime"),
        table_name="funding_history",
        schema="reports",
    )
    op.drop_table("funding_history", schema="reports")
    op.drop_index(
        op.f("ix_reports_apy_rate_history_partner_name"),
        table_name="apy_rate_history",
        schema="reports",
    )
    op.drop_index(
        op.f("ix_reports_apy_rate_history_datetime"),
        table_name="apy_rate_history",
        schema="reports",
    )
    op.drop_table("apy_rate_history", schema="reports")
    # ### end Alembic commands ###
