"""Add group schema and relationship to vault

Revision ID: 9c8725467e5d
Revises: 5cc6cf68ef68
Create Date: 2024-07-13 06:51:32.217006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c8725467e5d'
down_revision: Union[str, None] = '5cc6cf68ef68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_groups',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vaults', sa.Column('tvl', sa.Float(), nullable=True))
    op.add_column('vaults', sa.Column('group_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'vaults', 'vault_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaults', type_='foreignkey')
    op.drop_column('vaults', 'group_id')
    op.drop_column('vaults', 'tvl')
    op.drop_table('vault_groups')
    # ### end Alembic commands ###
