"""Add UserHoldingJobState table

Revision ID: 9ef41c17b3e7
Revises: 8c19a4f43231
Create Date: 2024-08-15 21:19:01.669838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9ef41c17b3e7"
down_revision: Union[str, None] = "8c19a4f43231"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_holding_job_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vault_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_positions", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cumulative_deployment_fund", sa.Float(), nullable=False),
        sa.Column("latest_block", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_holding_job_state_timestamp"),
        "user_holding_job_state",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_holding_job_state_timestamp"), table_name="user_holding_job_state"
    )
    op.drop_table("user_holding_job_state")
    # ### end Alembic commands ###
