"""add_vault_rewards

Revision ID: a75b381eb89c
Revises: 7e42c3186e9b
Create Date: 2024-10-09 17:26:52.208764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a75b381eb89c"
down_revision: Union[str, None] = "7e42c3186e9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vault_reward_history",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("vault_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("earned_rewards", sa.Float(), nullable=True),
        sa.Column("unclaimed_rewards", sa.Float(), nullable=True),
        sa.Column("claimed_rewards", sa.Float(), nullable=True),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vault_reward_history_datetime"),
        "vault_reward_history",
        ["datetime"],
        unique=False,
    )
    op.create_table(
        "vault_rewards",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("vault_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("earned_rewards", sa.Float(), nullable=True),
        sa.Column("unclaimed_rewards", sa.Float(), nullable=True),
        sa.Column("claimed_rewards", sa.Float(), nullable=True),
        sa.Column("token_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.alter_column(
        "vault_reward_history",
        "datetime",
        existing_type=sa.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        postgresql_using="datetime AT TIME ZONE 'UTC'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("vault_rewards")
    op.drop_index(
        op.f("ix_vault_reward_history_datetime"), table_name="vault_reward_history"
    )
    op.drop_table("vault_reward_history")
    # ### end Alembic commands ###
