"""Change datetime to TIMESTAMPTZ

Revision ID: aba99d6ecfac
Revises: 56ef659cac65
Create Date: 2024-09-15 14:41:53.541006

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aba99d6ecfac"
down_revision: Union[str, None] = "56ef659cac65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "vault_performance",
        "datetime",
        existing_type=sa.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        postgresql_using="datetime AT TIME ZONE 'UTC'",
    )
    op.alter_column(
        "vault_performance_history",
        "datetime",
        existing_type=sa.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        postgresql_using="datetime AT TIME ZONE 'UTC'",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
