"""add_vault_metadata

Revision ID: ac931da41452
Revises: cac8624add7e
Create Date: 2024-09-17 14:30:56.073542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ac931da41452"
down_revision: Union[str, None] = "cac8624add7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vault_metadata",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("vault_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("leverage", sa.Float(), nullable=True),
        sa.Column("borrow_apr", sa.Float(), nullable=True),
        sa.Column("health_factor", sa.Float(), nullable=True),
        sa.Column("open_position", sa.Float(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["vaults.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.alter_column(
        "vault_metadata",
        "last_updated",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vault_metadata")
    # ### end Alembic commands ###
