"""Add session_id to referral_points

Revision ID: e44b0c50293a
Revises: 009e2679df27
Create Date: 2024-07-15 01:06:16.841672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e44b0c50293a'
down_revision: Union[str, None] = '009e2679df27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_points', sa.Column('session_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'referral_points', 'reward_sessions', ['session_id'], ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referral_points', type_='foreignkey')
    op.drop_column('referral_points', 'session_id')
    # ### end Alembic commands ###
