"""add_report_funding_rate

Revision ID: e55cf2c87675
Revises: a176b1b01a45
Create Date: 2024-12-08 18:23:02.326458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "e55cf2c87675"
down_revision: Union[str, None] = "a176b1b01a45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funding_rate_history",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("funding_rate", sa.Float(), nullable=False),
        sa.Column("partner_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="reports",
    )
    op.create_index(
        op.f("ix_reports_funding_rate_history_datetime"),
        "funding_rate_history",
        ["datetime"],
        unique=False,
        schema="reports",
    )
    op.create_index(
        op.f("ix_reports_funding_rate_history_partner_name"),
        "funding_rate_history",
        ["partner_name"],
        unique=False,
        schema="reports",
    )
    op.create_table(
        "goldlink_borrow_rate_history",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("apy_rate", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="reports",
    )
    op.create_index(
        op.f("ix_reports_goldlink_borrow_rate_history_datetime"),
        "goldlink_borrow_rate_history",
        ["datetime"],
        unique=False,
        schema="reports",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reports_goldlink_borrow_rate_history_datetime"),
        table_name="goldlink_borrow_rate_history",
        schema="reports",
    )
    op.drop_table("goldlink_borrow_rate_history", schema="reports")
    op.drop_index(
        op.f("ix_reports_funding_rate_history_partner_name"),
        table_name="funding_rate_history",
        schema="reports",
    )
    op.drop_index(
        op.f("ix_reports_funding_rate_history_datetime"),
        table_name="funding_rate_history",
        schema="reports",
    )
    op.drop_table("funding_rate_history", schema="reports")
    # ### end Alembic commands ###
