"""add_projected_apy

Revision ID: fdcea60a9dbd
Revises: a44c909f1b99
Create Date: 2024-11-14 11:51:18.077172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fdcea60a9dbd"
down_revision: Union[str, None] = "a44c909f1b99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vault_performance", sa.Column("projected_apy", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("vault_performance", "projected_apy")
    # ### end Alembic commands ###
