"""add whitelist wallets table in config schema

Revision ID: ff101077736c
Revises: e55cf2c87675
Create Date: 2024-12-20 14:27:28.099212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "ff101077736c"
down_revision: Union[str, None] = "e55cf2c87675"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create config schema if it doesn't exist
    op.execute('CREATE SCHEMA IF NOT EXISTS config')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whitelist_wallets",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("vault_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("wallet_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="config",
    )
    op.create_index(
        op.f("ix_config_whitelist_wallets_vault_slug"),
        "whitelist_wallets",
        ["vault_slug"],
        unique=False,
        schema="config",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        op.f("ix_config_whitelist_wallets_vault_slug"),
        table_name="whitelist_wallets",
        schema="config",
    )
    op.drop_table("whitelist_wallets", schema="config")
    # ### end Alembic commands ###
