from enum import Enum


class APYComponent(Enum):
    EZ_ETH = "EZ_ETH"
    AE_USD = "AE_USD"
    RS_ETH = "RS_ETH"
    WST_ETH = "WST_ETH"
    FUNDING_FEES = "FUNDING_FEES"
    OPTIONS_YIELD = "OPTIONS_YIELD"
    USDCe_USDC = "USDCe_USDC"
    BSX_POINT = "BSX_POINT"
    ETH_GAINS = "ETH_GAINS"
    FIXED_YIELD = "FIXED_YIELD"
    ARB_REWARDS = "ARB_REWARDS"
